import homepage from './homepage'
import carousel from './carousel'
import game from './game'
import engine from './engine'
import about from './about'
import sectionCard from './components/card'
import socials from './components/socials'
import richText from './common/richText'
import media from './common/media'
import video from './common/video'
import files from './common/files'
import socialProfile from './common/socialProfile'
import businessCard from './common/businessCard'

export const schemaTypes = [homepage,carousel, game, engine, about, sectionCard, socials, richText, media, video, files, socialProfile, businessCard]
